# image size 448
# Serial 20: 4 PTs, 4 KRs, 10 Datasets
# Serial 30 (CLCA): 9 PTs, 10 Datasets, 5 KRs
# Serial 60: Tiny
# python plot.py --keep_serials 60 --keep_methods bl clca --type_plot box --x_var_name kr --y_var_name acc --hue_var_name method --output_file box_acc_vs_kr_method_20_30_60_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"
# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot box --x_var_name kr --y_var_name acc --hue_var_name method --output_file box_acc_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"

# python plot.py --keep_serials 60 --keep_methods bl clca --type_plot box --x_var_name pt --y_var_name acc --hue_var_name method --output_file box_acc_vs_pt_method_20_30_60_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"
# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot box --x_var_name pt --y_var_name acc --hue_var_name method --output_file box_acc_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"

# python plot.py --keep_serials 60 --keep_methods bl clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file box_acc_vs_ds_method_20_30_60_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 KRs) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"
# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file box_acc_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 KRs) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"

# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot violin --x_var_name pt --y_var_name acc --hue_var_name method --output_file violin_acc_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"
# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot violin --x_var_name kr --y_var_name acc --hue_var_name method --output_file violin_acc_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"
# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot violin --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file violin_acc_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 Keep Rates) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"

# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot box --x_var_name pt --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Std. Dev. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone" --y_label "Acc. Std. Dev. (%)"
# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot box --x_var_name kr --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Std. Dev. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)" --y_label "Acc. Std. Dev. (%)"
# python plot.py --keep_serials 60 --keep_methods bl cla clca --type_plot box --x_var_name dataset_name --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Std. Dev. Distribution (9 Backbones, 5 Keep Rates) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)" --y_label "Acc. Std. Dev. (%)"


# python plot.py --keep_serials 30 --keep_methods bl clca --type_plot box --x_var_name kr --y_var_name acc --hue_var_name method --output_file box_acc_vs_kr_method_20_30_60_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"
# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot box --x_var_name kr --y_var_name acc --hue_var_name method --output_file box_acc_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"

# python plot.py --keep_serials 30 --keep_methods bl clca --type_plot box --x_var_name pt --y_var_name acc --hue_var_name method --output_file box_acc_vs_pt_method_20_30_60_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"
# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot box --x_var_name pt --y_var_name acc --hue_var_name method --output_file box_acc_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"

# python plot.py --keep_serials 30 --keep_methods bl clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file box_acc_vs_ds_method_20_30_60_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 KRs) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"
# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file box_acc_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 KRs) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"

# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot violin --x_var_name pt --y_var_name acc --hue_var_name method --output_file violin_acc_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"
# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot violin --x_var_name kr --y_var_name acc --hue_var_name method --output_file violin_acc_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"
# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot violin --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file violin_acc_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 Keep Rates) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"

# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot box --x_var_name pt --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Std. Dev. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone" --y_label "Acc. Std. Dev. (%)"
# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot box --x_var_name kr --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Std. Dev. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)" --y_label "Acc. Std. Dev. (%)"
# python plot.py --keep_serials 30 --keep_methods bl cla clca --type_plot box --x_var_name dataset_name --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Std. Dev. Distribution (9 Backbones, 5 Keep Rates) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)" --y_label "Acc. Std. Dev. (%)"

# Only 4 PTs in serial 20: Deit, 2 * Deit3, Clip
python plot.py --keep_krs 0.1 0.25 0.5 0.7 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b --keep_datasets cotton soylocal soyageing soyglobal soygene soyageingr1 soyageingr3 soyageingr4 soyageingr5 soyageingr6 --keep_serials 20 30 --keep_methods clca --type_plot box --x_var_name tr --y_var_name acc --hue_var_name method --output_file box_acc_vs_tr_method_20_30_title --fig_size 7 4 --title "Acc. Distribution (4 Backbones, 4 KRs, 10 Datasets) for SotA TR Schemes" --x_label  "Token Reduction (TR) Scheme"
python plot.py --keep_krs 0.1 0.25 0.5 0.7 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b --keep_datasets cotton soylocal soyageing soyglobal soygene --keep_serials 20 30 --keep_methods clca --type_plot box --x_var_name tr --y_var_name acc --hue_var_name method --output_file box_acc_vs_tr_method_20_30_ufgir_title --fig_size 7 4 --title "Acc. Distribution (4 Backbones, 4 KRs, 5 Datasets) for SotA TR Schemes" --x_label  "Token Reduction (TR) Scheme"
python plot.py --keep_krs 0.1 0.25 0.5 0.7 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b --keep_datasets soyageingr1 soyageingr3 soyageingr4 soyageingr5 soyageingr6 --keep_serials 20 30 --keep_methods clca --type_plot box --x_var_name tr --y_var_name acc --hue_var_name method --output_file box_acc_vs_tr_method_20_30_soyageing_title --fig_size 7 4 --title "Acc. Distribution (4 Backbones, 4 KRs, 5 Soyageing Datasets) for SotA TR Schemes" --x_label  "Token Reduction (TR) Scheme"

python plot.py --keep_datasets cotton soylocal soyageing soyglobal soygene --keep_serials 20 30 --keep_krs 0.1 0.25 0.5 0.7 --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_20_30_ufgir     --fig_size 7 4 --title "Acc. Dist. (4 Backbones, 4 KRs) Grouped by DS and TR Schemes"   --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets cotton soylocal soyageing soyglobal soygene --keep_serials 20 30 --keep_krs 0.1              --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_010_20_30_ufgir --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.1) Grouped by DS and TR Schemes"  --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets cotton soylocal soyageing soyglobal soygene --keep_serials 20 30 --keep_krs 0.25             --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_025_20_30_ufgir --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.25) Grouped by DS and TR Schemes" --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets cotton soylocal soyageing soyglobal soygene --keep_serials 20 30 --keep_krs 0.5              --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_050_20_30_ufgir --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.5) Grouped by DS and TR Schemes"  --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets cotton soylocal soyageing soyglobal soygene --keep_serials 20 30 --keep_krs 0.7              --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_070_20_30_ufgir --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.7) Grouped by DS and TR Schemes"  --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b

python plot.py --keep_datasets soyageingr1 soyageingr3 soyageingr4 soyageingr5 soyageingr6 --keep_serials 20 30 --keep_krs 0.1 0.25 0.5 0.7 --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_20_30_soyageing     --fig_size 7 4 --title "Acc. Dist. (4 Backbones, 4 KRs) Grouped by DS and TR Schemes"   --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets soyageingr1 soyageingr3 soyageingr4 soyageingr5 soyageingr6 --keep_serials 20 30 --keep_krs 0.1              --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_010_20_30_soyageing --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.1) Grouped by DS and TR Schemes"  --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets soyageingr1 soyageingr3 soyageingr4 soyageingr5 soyageingr6 --keep_serials 20 30 --keep_krs 0.25             --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_025_20_30_soyageing --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.25) Grouped by DS and TR Schemes" --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets soyageingr1 soyageingr3 soyageingr4 soyageingr5 soyageingr6 --keep_serials 20 30 --keep_krs 0.5              --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_050_20_30_soyageing --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.5) Grouped by DS and TR Schemes"  --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b
python plot.py --keep_datasets soyageingr1 soyageingr3 soyageingr4 soyageingr5 soyageingr6 --keep_serials 20 30 --keep_krs 0.7              --keep_methods clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name tr --output_file box_acc_vs_ds_tr_clca_070_20_30_soyageing --fig_size 7 4 --title "Acc. Dist. (4 Backbones, KR=0.7) Grouped by DS and TR Schemes"  --x_label  "Dataset Name (DS)" --loc_legend "lower left" --legend_ncol 2 --keep_pts deit_base_patch16_224.fb_in1k deit3_base_patch16_224.fb_in22k_ft_in1k deit3_base_patch16_224.fb_in1k vit_base_patch16_clip_224.laion2b

python plot.py --keep_serials 20 30 --keep_methods bl clca --type_plot box --x_var_name kr --y_var_name acc --hue_var_name method --output_file box_acc_vs_kr_method_20_30_60_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"

python plot.py --keep_serials 20 30 --keep_methods bl clca --type_plot box --x_var_name pt --y_var_name acc --hue_var_name method --output_file box_acc_vs_pt_method_20_30_60_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"

python plot.py --keep_serials 20 30 --keep_methods bl clca --type_plot box --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file box_acc_vs_ds_method_20_30_60_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 KRs) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"

python plot.py --keep_serials 20 30 --keep_methods bl cla clca --type_plot violin --x_var_name pt --y_var_name acc --hue_var_name method --output_file violin_acc_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone"
python plot.py --keep_serials 20 30 --keep_methods bl cla clca --type_plot violin --x_var_name kr --y_var_name acc --hue_var_name method --output_file violin_acc_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)"
python plot.py --keep_serials 20 30 --keep_methods bl cla clca --type_plot violin --x_var_name dataset_name --y_var_name acc --hue_var_name method --output_file violin_acc_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Distribution (9 Backbones, 5 Keep Rates) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)"

python plot.py --keep_serials 20 30 --keep_methods bl cla clca --type_plot box --x_var_name pt --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_pt_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Std. Dev. Distribution (5 Keep Rates, 10 Datasets) for SotA PT Backbones w/ and w/o CLCA" --x_label "Pretrained (PT) Backbone" --y_label "Acc. Std. Dev. (%)"
python plot.py --keep_serials 20 30 --keep_methods bl cla clca --type_plot box --x_var_name kr --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_kr_method_20_30_60_detail_title --fig_size 6 4 --title "Acc. Std. Dev. Distribution (9 Backbones, 10 Datasets) for KRs w/ and w/o CLCA" --x_label "Keep Rate (KR, %)" --y_label "Acc. Std. Dev. (%)"
python plot.py --keep_serials 20 30 --keep_methods bl cla clca --type_plot box --x_var_name dataset_name --y_var_name acc_std --hue_var_name method --output_file box_acc_stdev_vs_ds_method_20_30_60_detail_title --fig_size 9 4 --x_rotation 30 --title "Acc. Std. Dev. Distribution (9 Backbones, 5 Keep Rates) for Datasets w/ and w/o CLCA" --x_label "Dataset Name (DS)" --y_label "Acc. Std. Dev. (%)"
